[package]
name = "counter-call"
version = "0.1.0"
authors = ["Michael Birch <birchmd@casperlabs.io>"]
edition = "2018"

[lib]
name = "countercall"
crate-type = ["cdylib"]

[dependencies]
contract-ffi = { package = "casperlabs-contract-ffi", version = "0.18.0" }
