version: "3.5"

volumes:
  # Volume to be shared between the execution engine and the node.
  socketvolume: {}

services:

  node:
    image: casperlabs/node:latest
    container_name: contract-examples_node
    volumes:
      - socketvolume:/root/.casperlabs/sockets
      # Mount the bonds.txt corresponding to the validator public key.
      # If we don't specify a key to use when starting the node it will
      # be in read-only mode and we can't deploy anything.
      - $PWD/.casperlabs/genesis:/root/.casperlabs/genesis
    ports:
      # gRPC port for the client to talk to.
      - ${CL_GRPC_PORT_EXTERNAL}:40401
    command:
      - run
      - -s
      - --casper-validator-public-key
      - 6736848c09979653d84edea6244c7b13a3cbbfcfd9f6c104ca7600aa9d6e7bfa
      - --casper-validator-private-key
      - 2fe69b4b74c05a594eafb486c86f88fc42b94aca440a6eba8cd3c20c73eb96b6
      - --grpc-socket
      - /root/.casperlabs/sockets/.casper-node.sock
    depends_on:
      - execution-engine

  execution-engine:
    image: casperlabs/execution-engine:latest
    container_name: contract-examples_execution-engine
    volumes:
      - socketvolume:/opt/docker/.casperlabs/sockets
    command:
      - .casperlabs/sockets/.casper-node.sock
