[package]
name = "mailing-list-define"
version = "0.1.0"
authors = ["Michael Birch <birchmd@casperlabs.io>"]

[lib]
name = "mailinglistdefine"
crate-type = ["cdylib"]

[dependencies]
contract-ffi = {package = "casperlabs-contract-ffi", version = "0.12.0" }
