[package]
name = "store-hello-name"
version = "0.1.0"
authors = ["Michael Birch <birchmd@casperlabs.io>"]

[lib]
name = "helloname"
crate-type = ["cdylib"]

[dependencies]
common = { package = "casperlabs-contract-ffi", version = "^0" }
