[package]
name = "get-caller-define"
version = "0.1.0"
authors = ["Mateusz Górski mateusz@casperlabs.io"]

[lib]
name = "getcallerdefine"
crate-type = ["cdylib"]

[dependencies]
common = { package = "casperlabs-contract-ffi", version = "0.8.0" }

