[package]
name = "counter-define"
version = "0.1.0"
authors = ["Michael Birch <birchmd@casperlabs.io>"]
edition = "2018"

[lib]
name = "counterdefine"
crate-type = ["cdylib"]

[dependencies]
contract-ffi = { package = "casperlabs-contract-ffi", version = "0.17.0" }
